import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

import MenuCategory from "@/components/MenuCategory";
import ScrollToTop from "@/components/ScroolToTop";
import Footer from "../components/Footer";
import Header from "../components/Header";
import "./globals.css";

const notoSansKR = Noto_Sans_KR({
  weight: ["100", "100", "300", "400", "500", "700", "900"],
  subsets: ["latin-ext"],
  variable: "--font-noto-sans-kr",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.variable} noto-sans-kr-font`}>
        <div className="bg-black min-h-screen text-white">
          <Header />
          {children}
          <Footer />
          <ScrollToTop />
          <MenuCategory />
        </div>
      </body>
    </html>
  );
}
