import type { Metadata } from 'next';
import './globals.css';
import { LoadingProvider } from '@/contexts/LoadingContext';
import { MovieProvider } from '@/hooks/useMoviesContext';
import Header from '@/component/Header';
import NavBar from '@/component/NavBar';
import { NextUIProvider } from '@nextui-org/react';
import Title from '@/component/Title';
import Footer from '@/component/Footer';
import MobileNav from '@/component/MobileNav';

export const metadata: Metadata = {
  title: 'Movie Professional',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <LoadingProvider>
            <MovieProvider>
              <Header />
              <Title />
              <div className="flex">
                <NavBar />
                <main className="flex-1">{children}</main>
              </div>
              <Footer />
              <MobileNav />
            </MovieProvider>
          </LoadingProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
