import type { Metadata } from 'next';
import './globals.css';
import { LoadingProvider } from '@/contexts/LoadingContext';
import { MovieProvider } from '@/hooks/useMoviesContext';

export const metadata: Metadata = {
  title: 'Movie Professional',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoadingProvider>
          <MovieProvider>{children}</MovieProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
